language: java
jdk:
  - openjdk8

branches:
  only:
    - master

## ------------추가 부분----------------
#
#before_script:
#  - cd springweb/

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - harrison1995@naver.com
  slack: springwebhq:i0bqFSEuqchMWdkP7XMGBYuP