# 언어와 jdk 버전 지정
language: java
jdk:
  - openjdk8

# 오직 master 브랜치에 push될 때만 수행되도록함
branches:
  only:
    - master

# 빌드 전 gradlew에 대한 실행권한 주기
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받으면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때 부터 다시 받지 않도록 함
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 push 되었을 때 수행되는 명령어
script: "./gradlew clean build"

# CI 실행 완료시 메일,슬랙으로 알람
notifications:
  email:
    recipients:
      - harrison1995@naver.com
  slack: springwebhq:i0bqFSEuqchMWdkP7XMGBYuP

before_deploy:
  - zip -r springweb *
  - mkdir -p deploy
  - mv springweb.zip deploy/springweb.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springweb-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: kimgun95/springweb #Github 주소
      branch: master
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springweb-deploy # S3 버킷
    key: springweb.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springweb # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springweb-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: kimgun95/springweb
      branch: master