spring:
  profiles:
    active: local # 기본 환경 선택
  main:
    allow-circular-references: true

# local 환경
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
